const productsData = [
  {
    id: 1,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'EcoCleanPro Vacuum',
    description: 'Powerful and eco-friendly vacuum cleaner',
    buttonText: 'Learn now!',
    price: '$199.99',
    link: '/product/ecocleanpro-vacuum',
    category: 'Electronics',
  },
  {
    id: 2,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'TechMaster Smartwatch',
    description: 'Stay connected with our advanced smartwatch',
    buttonText: 'Learn now!',
    price: '$149.99',
    link: '/product/techmaster-smartwatch',
    category: 'Electronics',
  },
  {
    id: 3,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'FreshHarvest Organic Soap',
    description: 'Experience purity with our natural organic soap',
    buttonText: 'Learn now!',
    price: '$9.99',
    link: '/product/freshharvest-organic-soap',
    category: 'Personal Care',
  },
  {
    id: 4,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'AquaFlow Water Purifier',
    description: 'Pure and refreshing water for your home',
    buttonText: 'Learn now!',
    price: '$129.99',
    link: '/product/aquaflow-water-purifier',
    category: 'Home & Kitchen',
  },
  {
    id: 5,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'SwiftServe Food Delivery App',
    description: 'Enjoy a wide variety of cuisines at your doorstep',
    buttonText: 'Learn now!',
    price: 'Free',
    link: '/product/swiftserve-food-delivery',
    category: 'Apps & Software',
  },
  {
    id: 6,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'EcoGarden Solar Lights',
    description: 'Illuminate your garden with sustainable solar lights',
    buttonText: 'Learn now!',
    price: '$49.99',
    link: '/product/ecogarden-solar-lights',
    category: 'Outdoor Living',
  },
  {
    id: 7,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'ComfortZone Memory Foam Pillow',
    description: 'Sink into a cloud of comfort with our memory foam pillow',
    buttonText: 'Learn now!',
    price: '$39.99',
    link: '/product/comfortzone-memory-foam-pillow',
    category: 'Bedding & Home',
  },
  {
    id: 8,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'FitFuel Protein Shake',
    description: 'Fuel your workouts with our high-protein shake',
    buttonText: 'Learn now!',
    price: '$29.99',
    link: '/product/fitfuel-protein-shake',
    category: 'Fitness & Nutrition',
  },
  {
    id: 9,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'LuxuryLounge Sofa Set',
    description: 'Elevate your living space with our luxurious sofa set',
    buttonText: 'Learn now!',
    price: '$599.99',
    link: '/product/luxurylounge-sofa-set',
    category: 'Furniture',
  },
  {
    id: 10,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'EcoCleanPro Vacuum',
    description: 'Powerful and eco-friendly vacuum cleaner',
    buttonText: 'Learn now!',
    price: '$199.99',
    link: '/product/ecocleanpro-vacuum',
    category: 'Electronics',
  },
  {
    id: 11,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'TechMaster Smartwatch',
    description: 'Stay connected with our advanced smartwatch',
    buttonText: 'Learn now!',
    price: '$149.99',
    link: '/product/techmaster-smartwatch',
    category: 'Electronics',
  },
  {
    id: 12,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'FreshHarvest Organic Soap',
    description: 'Experience purity with our natural organic soap',
    buttonText: 'Learn now!',
    price: '$9.99',
    link: '/product/freshharvest-organic-soap',
    category: 'Personal Care',
  },
  {
    id: 13,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'AquaFlow Water Purifier',
    description: 'Pure and refreshing water for your home',
    buttonText: 'Learn now!',
    price: '$129.99',
    link: '/product/aquaflow-water-purifier',
    category: 'Home & Kitchen',
  },
  {
    id: 14,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'SwiftServe Food Delivery App',
    description: 'Enjoy a wide variety of cuisines at your doorstep',
    buttonText: 'Learn now!',
    price: 'Free',
    link: '/product/swiftserve-food-delivery',
    category: 'Apps & Software',
  },
  {
    id: 15,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'EcoGarden Solar Lights',
    description: 'Illuminate your garden with sustainable solar lights',
    buttonText: 'Learn now!',
    price: '$49.99',
    link: '/product/ecogarden-solar-lights',
    category: 'Outdoor Living',
  },
  {
    id: 16,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'ComfortZone Memory Foam Pillow',
    description: 'Sink into a cloud of comfort with our memory foam pillow',
    buttonText: 'Learn now!',
    price: '$39.99',
    link: '/product/comfortzone-memory-foam-pillow',
    category: 'Bedding & Home',
  },
  {
    id: 17,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'FitFuel Protein Shake',
    description: 'Fuel your workouts with our high-protein shake',
    buttonText: 'Learn now!',
    price: '$29.99',
    link: '/product/fitfuel-protein-shake',
    category: 'Fitness & Nutrition',
  },
  {
    id: 18,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'LuxuryLounge Sofa Set',
    description: 'Elevate your living space with our luxurious sofa set',
    buttonText: 'Learn now!',
    price: '$599.99',
    link: '/product/luxurylounge-sofa-set',
    category: 'Furniture',
  },
  {
    id: 19,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'EcoCleanPro Vacuum',
    description: 'Powerful and eco-friendly vacuum cleaner',
    buttonText: 'Learn now!',
    price: '$199.99',
    link: '/product/ecocleanpro-vacuum',
    category: 'Electronics',
  },
  {
    id: 20,
    imageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/oversizedtshirt.webp',
    hoverImageSrc: 'https://codeswear.nyc3.cdn.digitaloceanspaces.com/constants/landing/collections/mousepad.webp',
    title: 'SereneSpace Meditation Cushion',
    description: 'Experience tranquility with our premium meditation cushion',
    buttonText: 'Learn now!',
    price: '$69.99',
    link: '/product/serenespace-meditation-cushion',
    category: 'Wellness',
  },
];

export default productsData;
