import GoToTopButton from '@/components/GoToTopButton'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html data-theme="synthwave" lang="en">
      <body className={inter.className}>{children}</body>
      <GoToTopButton/>
      <Sidebar/>
      <Footer/>
    </html>
  )
}
