import GoToTopButton from '@/components/GoToTopButton'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import Footer from '@/components/Footer'
import { ThemeProvider } from '@/components/ThemeContext'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>

    <html  lang="en">
      <body>
      <Navbar/>
        {children}
        </body>
      <GoToTopButton/>
      <Sidebar/>
      <Footer/>
    </html>
    </ThemeProvider>
  )
}
