import dynamic from 'next/dynamic';
import React from 'react';
import GoToTopButton from '@/components/GoToTopButton';
import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/components/ThemeContext';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body>
          <Navbar />
          <main>{children}</main> {/* Place your page content here */}
          <GoToTopButton />
          <Sidebar />
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
